# Generated by Django 5.0.2 on 2024-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_views',
            field=models.IntegerField(default=0),
        ),
    ]
